### ISSUE TITLE
Npm start doesnt work on latest Node

### ISSUE THREAD

**Issue by drewwiskus** [mjmlio/mjml-component-boilerplate#24]
```
> test@1.0.1 start /Users/redacted/redacted/redacted/component_boilerplate
> gulp watch

[13:55:13] Failed to load external module @babel/register
[13:55:13] Requiring external module babel-register
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
at fs.js:27:26
at req_ (/Users/redacted/redacted/redacted/component_boilerplate/node_modules/vinyl-fs/node_modules/graceful-fs/node_modules/natives/index.js:137:5)
at Object.req [as require] (/Users/redacted/redacted/redacted/component_boilerplate/node_modules/vinyl-fs/node_modules/graceful-fs/node_modules/natives/index.js:54:10)
at Object.<anonymous> (/Users/redacted/redacted/redacted/component_boilerplate/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
at Module._compile (internal/modules/cjs/loader.js:774:30)
at Module._extensions..js (internal/modules/cjs/loader.js:785:10)
at Object.require.extensions.<computed> [as .js] (/Users/redacted/redacted/redacted/component_boilerplate/node_modules/babel-register/lib/node.js:152:7)
at Module.load (internal/modules/cjs/loader.js:641:32)
at Function.Module._load (internal/modules/cjs/loader.js:556:12)
at Module.require (internal/modules/cjs/loader.js:681:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@1.0.1 start: `gulp watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the test@1.0.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

running on Node v12.4.0

would be awesome if this was fixed on a repo level :) is there any way to fix this without downgrading the Node version I use?

**Comment by iRyusa** [comment]
Looks like it's an issue with older graceful-fs dep. I'll see what can we do about this.

**Comment by drewwiskus** [comment]
Thank you! I really love mjml and this would really help streamline onboarding of new devs on my team :)

**Comment by AndyBaird** [comment]
I am having a similar issue but am on Node v11.6.0. `npm install` produces about 20 errors and `gulp build` produces the following:
`~/D/p/mjml-component-boilerplate   master ±  gulp build
[13:47:39] Requiring external module babel-register
fs.js:25
'use strict';
^

ReferenceError: internalBinding is not defined
    at fs.js:25:1`

**Comment by iRyusa** [comment]
@AndyBaird  & @drewwiskus I've opened a PR can you try on your side with this branch if this is ok for you ?
Tested with node v12.14.0 and it's ok
