### ISSUE TITLE
Error: "Missing or unreadable custom component" on first build

### ISSUE THREAD

**Issue by vtherry** [mjmlio/mjml-component-boilerplate#32]
Hi,

after cloning the repo, running `npm install` and `gulp build`, I am facing the following error :

[16:16:06] Requiring external module @babel/register
Missing or unreadable custom component :  ./lib/MjBasicComponent.js
Missing or unreadable custom component :  ./lib/MjImageText.js
Missing or unreadable custom component :  ./lib/MjLayout.js
[16:16:09] Using gulpfile C:\projects\mjml-components-boilerplate\gulpfile.babel.js
[16:16:09] Starting 'build'...
[16:16:09] 'build' errored after 337 ms
[16:16:09] Error: Cannot find module 'C:\projects\mjml-components-boilerplate\lib\MjBasicComponent.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at forEach (C:\projects\mjml-components-boilerplate\/gulpfile.babel.js:33:27)
    at Array.forEach (<anonymous>)
    at Pumpify.<anonymous> (C:\projects\mjml-components-boilerplate\/gulpfile.babel.js:30:25)
    at Pumpify.emit (events.js:194:15)
    at Pumpify.EventEmitter.emit (domain.js:459:23)
    at endReadableNT (C:\projects\mjml-components-boilerplate\node_modules\duplexify\node_modules\readable-stream\lib\_stream_readable.js:1010:12)

I found my file structure to be :
- .\lib\components\MjBasicComponent.js
- .\lib\components\MjImageText.js
- .\lib\components\MjLayout.js

I'm on Windows

**Comment by vtherry** [comment]
Duplicate of https://github.com/mjmlio/mjml-component-boilerplate/issues/28
