### ISSUE TITLE
TypeError: Cannot read property 'mjml' of undefined

### ISSUE THREAD

**Issue by gabrieltomescu** [mjmlio/mjml-component-boilerplate#6]
Hi, 

This is probably an easy fix, but I'm having trouble building a very simple component.

The error I'm seeing is this:
```
[11:03:43] Starting 'build'...
[11:03:43] Finished 'build' after 15 ms
> MJML compilation failed:

TypeError: Cannot read property 'mjml' of undefined
    at /Users/gtomescu/Work/code/ripple/node_modules/mjml-core/lib/decorators/MJMLElement.js:137:30
    at Array.filter (native)
    at MJMLElement._this.renderWrappedOutlookChildren (/Users/gtomescu/Work/code/ripple/node_modules/mjml-core/lib/decorators/MJMLElement.js:136:37)
    at Section.renderSection (/Users/gtomescu/Work/code/ripple/node_modules/mjml-section/lib/index.js:243:17)
    at Section.render (/Users/gtomescu/Work/code/ripple/node_modules/mjml-section/lib/index.js:253:72)
    at /Users/gtomescu/Work/code/ripple/node_modules/react-dom/lib/ReactCompositeComponent.js:796:21
    at measureLifeCyclePerf (/Users/gtomescu/Work/code/ripple/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (/Users/gtomescu/Work/code/ripple/node_modules/react-dom/lib/ReactCompositeComponent.js:795:25)
    at ReactCompositeComponentWrapper._renderValidatedComponent (/Users/gtomescu/Work/code/ripple/node_modules/react-dom/lib/ReactCompositeComponent.js:822:32)
    at ReactCompositeComponentWrapper.performInitialMount (/Users/gtomescu/Work/code/ripple/node_modules/react-dom/lib/ReactCompositeComponent.js:362:30)
```

And here's my code for testimonial.js:

```
import { MJMLElement } from 'mjml-core';
import React, { Component } from 'react';
import Section from 'mjml-section';
import Column from 'mjml-column';
import Image from 'mjml-image';
import Wrapper from 'mjml-wrapper';

// Tag Name
const tagName = 'testimonial';
// List of parent tags
const parentTag = ['mj-container'];
// If false, the component can contain MJML; if true, it can contain only plain HTML
const endingTag = false;
const defaultMJMLDefinition = {
  content: '',
  attributes: {
    'image-src': null,
    'image-align': 'center',
    'image-width': '40px',
  },
}

@MJMLElement
class Testimonial extends Component {

  renderAvatar () {
    const { mjAttribute } = this.props;

    return (
      <Section key="image">
        <Column>
          <Image align={mjAttribute('image-align')} width={mjAttribute('image-width')} src={mjAttribute('image-src')}/>
        </Column>
      </Section>
    )
  }

  render () {
    const { mjAttribute } = this.props;

    return (
      <Wrapper {...this.props}>
        this.renderAvatar();
      </Wrapper>
    )
  }
}

Testimonial.tagName = tagName;
Testimonial.parentTag = parentTag;
Testimonial.endingTag = endingTag;
Testimonial.defaultMJMLDefinition = defaultMJMLDefinition;

export default Testimonial;
```

Am I missing something?

**Comment by gabrieltomescu** [comment]
Figured it out.

**Comment by tjozwik** [comment]
I had the same issue on heroku builds. Deleting `package-lock.json` file worked for me. Anyway, I think it may not be a reasonable solution in many cases.
